spring.application.name=SaludVit

# PostgreSQL - Con valores por defecto para desarrollo local
spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d6jj7pma2pns73f8jllg-a.oregon-postgres.render.com:5432/saludvital}
spring.datasource.username=${DB_USERNAME:saludvital_user}
spring.datasource.password=${DB_PASSWORD:8EaSjvH2HsgYg1lG9IqkFngCuiA6UOq6}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=${PORT:8080}