spring.application.name=SaludVit

# PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d6jj7pma2pns73f8jllg-a.oregon-postgres.render.com:5432/saludvital
spring.datasource.username=saludvital_user
spring.datasource.password=8EaSjvH2HsgYg1lG9IqkFngCuiA6UOq6
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080